name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore AuthGate.sln

      - name: Build
        run: dotnet build AuthGate.sln -c Release --no-restore

      - name: Test
        run: dotnet test AuthGate.sln -c Release --no-build --verbosity normal

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: ./src/AuthGate.Auth
          file: ./src/AuthGate.Auth/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: authgate/auth:ci
