  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    strategy:
      matrix:
        svc:
          - name: auth
            context: ./src/AuthGate.Auth
            dockerfile: ./src/AuthGate.Auth/Dockerfile
            tag: authgate/auth:ci
          - name: mgmt
            context: ./src/AuthGate.Mgmt
            dockerfile: ./src/AuthGate.Mgmt/Dockerfile
            tag: authgate/mgmt:ci
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build ${{ matrix.svc.name }} image (no push)
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.svc.context }}
          file: ${{ matrix.svc.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ matrix.svc.tag }}
